# Quantum State Predictor
This course was taught by Dr. Theodore Corcovilos @corcoted, who presented the class with the Quantum Guessing Game. The game utilized the computer picking a random quantum spin-1/2 state from a predetermined list. The players (student teams) request measurements in the form of the Pauli operators $S_x$, $S_y$, or $S_z$ and attempt to guess the state. My student team **won** using a statistical method which thrives even with a low sample size (hint, Bayesian estimation).

But before the game, more on quantum properties.

# Background
### Quantum State
Generally, a state is what condition a system is in at a specific point in time. States are mathematical representations used in explanation of an object. For example, in classical mechanics the position and velocity vectors are mathematical entities describing the motion of an object in question. Quantum mechanics has a parallel to this descriptive format using bra-ket vectors. These pieces of notation do not convey the same physical representation that the position and velocity vectors do, rather they model the knowledge of a quantum system/particle. 


### Spin
Spin is an intrinsic property of all fundamental particles, with this project focused on spin-1/2 particles known as fermions. Fermions are the particles which build the matter of the universe, as opposed to bosons which have integer spin and are the force carriers. Examples of fermions include the proton, neutron, and electron among others. 

Spin is also referred to as the spin angular momentum quantum number, and is quantized using the reduced Planck constant $\frac{h}{2\pi}$ (h-bar). This number can be either positive or negative 1/2 for our particles of interest. 

### Spin-1/2 Quantum States
Just as a position vector in Cartesian 3-dimensional space can be written as components of the x, y, and z positions; similar methods are used for describing the state of a spin-1/2 particle. Quantum state vectors can be written in terms of the components of positive and negative spin, with a column vector in the form of (+, -). So, a positive spin-1/2 particle would have a vector representation of (1, 0), where the negative spin-1/2 is represented by (0, 1). For example, a state vector can be written as the linear combination seen as: $ \frac{1}{\sqrt{5}}(1, 0) + \frac{2}{\sqrt{5}}(0, 1) $.

Most important for the game at hand is how we try to retrieve the quantum states through measurements. There are three spin operators $S_x$, $S_y$, and $S_z$ which implement a spin measurement in their respective directions. Each have a 2x2 matrix notation with eigenvalues of positive and negative 1/2 times the reduced Planck constant. 

Hopefully, this background will provide a greater understanding to the guessing game and quantum mechanics in general. If you are looking for more information on this topic, Wikipedia can be very useful for quantum explanations.

# The Game

*   8 input states are provided in the form of Bloch vectors (vector with x, y, and z component of quantum representation) 
*   A quantum state is secretly chosen from the given possible states in a spin-1/2 system by the professor
* Then happening as many times necessary to guess the correct chosen state:
    1.   The student team requests a spin component measurement in a particular direction (x, y, or z)
    2.   Die is rolled to see if the measurement is (+) or (-) for the input state
    3.   Probabilities of the states resulting from the measurement are calculated
*   The team uses their algorithm to determine whether to either guess the true state or request another measurement in any direction for the same original state
*   Penalties are applied if incorrect state guesses are made and if too many measurements are made


## Our Task

Ultimately, our team (Rebecca Nelson, Duq '22 and myself) had to develop an algorithm to get the best possible score in the game, and especially a better score than the other student team. The algorithm is a deterministic set of rules that could only take spectific inputs:

*   Penalty rules
*   List of possible states
*   Table of probabilities and outcomes
*   Previous measurements and their results
*   Current score of your team and opponent team
*   Outcome of a random number generator


While producing outputs to inform us to make decisions on:

*   Which direction of measurement to request
*   When to guess and what state to guess

Ideally, we would guess the initial state correctly using the least number of measurements. 

In [1]:
import random
import numpy as np

Define input states and point system of game

In [2]:
random.seed()
# INPUT: given states as a matrix
# rows are each bloch vector
# columns are x, y, and z constants
inputstates = np.array([[0.612,-0.782,-0.118],
              [0.690,0.599,-0.408],
              [-0.706,-0.656,0.269],
              [-0.174,0.796,-0.580],
              [-0.577,-0.753,-0.315],
              [0.129,-0.967,0.220],
              [-0.221,0.588,0.778],
              [0.254,-0.340,-0.906]])
# count of given states
Ninputstates = inputstates.shape[0]

# define point system, per rules of the game
dsize = 20
maxguess = 20
penalty = 5

Define x, y, and z measurements

In [3]:
# defines what x, y, and, z mean
measurements = np.array([[1.,0.,0.],
                     [0.,1.,0.],
                     [0.,0.,1.]]) 
# count of measurement dimensions
Nmeasurements = measurements.shape[0]

Build lookup table for probability score of measuring (+) for each state

In [4]:
# initalize data structure
prob = np.zeros((measurements.shape[0],Ninputstates), dtype=int)
# calculate and fill matrix with probability scores
for i in range(measurements.shape[0]):
    for j in range(Ninputstates):
        prob[i, j] = (0.5*(1.0+np.dot(inputstates[j],measurements[i]))*dsize)
print(prob)

[[16 16  2  8  4 11  7 12]
 [ 2 15  3 17  2  0 15  6]
 [ 8  5 12  4  6 12 17  0]]


Our measurement guesses were facilitated with a random choice. By randomly selecting the x, y, or z dimension we gained a uniform distribution of state guesses to gain information from. 

In [26]:
# randomly select the x, y, or z dimension probability scores for measuring (+)
chooserow = prob[(random.randint(0,2)),:]
print(chooserow)

[ 2 15  3 17  2  0 15  6]


The die was physically rolled, with the professor saying whether the measurement resulted in (+) or (-). 

Due to the interactive nature of the game between code and real-time updating, we did not automate our algorithm.

In [27]:
# reassign out variable for each iteration of guesses
out = -1
print(out)

# based on measurement results, 
# calculate probability for each vector component
if (out==1):
    newValue=chooserow/20
    print(newValue)
else:
    newValue=(1-(chooserow/20))
    print(newValue)

-1
[0.9  0.25 0.85 0.15 0.9  1.   0.25 0.7 ]


# How we won: Bayesian Estimation

The quantum state guessing game is structured like golf, with the winning team having the lest number of measurements taken. Our team looked for a statistical method which would perform well with a small sample size (a small number of guesses). We saw great potential in Bayesian Estimation over the Method of Moments framework which uses expectation values to approximate the PDF and requires much larger sample sizes. 

### Conditional Probability

Bayes theorem is infinitely helpful as it makes use of conditional probability.

$P(A_i|B) = \frac{P(B|A_i) \cdot P(A_i)}{\sum_{i=1}^{i} P(B|A_i) \cdot P(A_i)}$

In short, Bayes theorem has four components; the posterior $P(A_i|B)$, likelihood $P(B|A_i)$, prior $P(A_i)$, and marginal.  The marginal (denominator) has been expanded to show the term in full as opposed to its usual representation as $P(B)$. 

Our team made use of not only Bayes theorem, but also the concept of Bayesian updating for our guessing algorithm. Follows is an example outlining Bayesian updating for the first two guesses of the quantum guessing game.

### Bayesian Updating Example

For our first guess we want to determine the probability of all states ($\Psi_1$ shown) being the true state given the measurement result of (+) in the x dimension. 

**Guess 1**

$P(State \; \Psi_1|+_x) = \frac{P(+_x|\Psi_1) \cdot P(\Psi_1)}{\sum_{i=1}^{i} P(+_x|\Psi_i) \cdot P(\Psi_i)}$

This posterior probability would be calculated for each of the 8 given quantum states, with the marginal incorporating each as a summation of probabilities (i = 8). The prior $P(\Psi_1)$ for the first guess was chosen to be uninformative (1/8) as an equal chance for each state vector. 

The second guess demonstrates Bayesian updating by using the **first guesses' posterior probability**. 

**Guess 2**

The second guess is the probability of all states ($\Psi_1$ shown) being the true state given the measurement result of (-) in the y dimension.

$P(State \; \Psi_1|-_y) = \frac{P(-_y|\Psi_1) \cdot P(State \; \Psi_1|+_x)}{\sum_{i=1}^{i} P(-_y|\Psi_i) \cdot P(State \; \Psi_1|+_x)}$

The posterior probability from guess 1, $P(State \; \Psi_1|+_x)$ is used in place of the original 1/8 for the prior term. By updating the prior, we can use information gained by each guess to inform the posterior calculation. 

----------------
## Bayes is the key

* Bayes Theorem allows us to continue making guesses without completely throwing out the previous information gained 
* It can still have high predictive power even with a small sample size (as compared with frequentist methods)

---------------

The following code shows the real-time game played against the rest of the class teams. We had code prepared beforehand and executed the blocks with each measurement taken and (+) or (-) state result. To decide when to make a final guess, we set a probabiloty threshold of 0.40. 

For each guess:
* `chooserow` is updated with random choice 
* `out` is manually changed based on the professor's direction (knowing the true final state)
* `newValue` (likelihood) is updated for each random choice of x, y, or z dimension

In [10]:
firstguess = np.zeros((newValue.shape[0], Ninputstates),dtype=float)
for i in range(1):
    for j in range(1):
        # bayes formula broken down 
        firstguess = newValue*(1/8)
        firstguess = firstguess/firstguess.sum()
        print(firstguess)

[0.125      0.15625    0.08333333 0.16666667 0.14583333 0.08333333
 0.03125    0.20833333]


In [13]:
secondguess = np.zeros((newValue.shape[0],Ninputstates),dtype=float)
for i in range(1):
    for j in range(1):
        # updated bayes equation with first guess as prior
        secondguess = newValue*firstguess
        secondguess = secondguess/secondguess.sum()
        print(secondguess)

[0.05111821 0.06389776 0.15335463 0.20447284 0.23855165 0.07667732
 0.04153355 0.17039404]


In [16]:
thirdguess=np.zeros((newValue.shape[0],Ninputstates),dtype=float)
for i in range(1):
    for j in range(1):
        # updated bayes equation with second guess as prior
        thirdguess=newValue*secondguess
        thirdguess=thirdguess/thirdguess.sum()
        print(thirdguess)

[0.10332302 0.12915377 0.03874613 0.20664604 0.12054352 0.10655186
 0.0367281  0.25830755]


In [22]:
fourthguess=np.zeros((newValue.shape[0],Ninputstates),dtype=float)
for i in range(1):
    for j in range(1):
        # updated bayes equation with third guess as prior
        fourthguess=newValue*thirdguess
        fourthguess=fourthguess/fourthguess.sum()
        print(fourthguess)

[0.15648453 0.05433491 0.0554216  0.05216151 0.18256529 0.17930519
 0.01545149 0.30427548]


In [25]:
fifthguess=np.zeros((newValue.shape[0],Ninputstates),dtype=float)
for i in range(1):
    for j in range(1):
        # updated bayes equation with fourth guess as prior
        fifthguess=newValue*fourthguess
        fifthguess=fifthguess/fifthguess.sum()
        print(fifthguess)

[0.06798415 0.17704207 0.03611658 0.19262177 0.07931485 0.
 0.05034634 0.39657424]


In [28]:
sixthguess=np.zeros((newValue.shape[0],Ninputstates),dtype=float)
for i in range(1):
    for j in range(1):
        # updated bayes equation with fifth guess as prior
        sixthguess=newValue*fifthguess
        sixthguess=sixthguess/sixthguess.sum()
        print (sixthguess)

[0.11618784 0.08404792 0.05829563 0.05486648 0.13555248 0.
 0.02390113 0.52714853]


In [ ]:
seventhguess=np.zeros((newValue.shape[0],Ninputstates),dtype=float)
for i in range(1):
    for j in range(1):
        # updated bayes equation with sixth guess as prior
        seventhguess=newValue*sixthguess
        seventhguess=seventhguess/seventhguess.sum()
        print (seventhguess)

In [ ]:
eigthguess=np.zeros((newValue.shape[0],Ninputstates),dtype=float)
for i in range(1):
    for j in range(1):
        # updated bayes equation with seventh guess as prior
        eigthguess=newValue*seventhguess
        eigthguess=eigthguess/eigthguess.sum()
        print (eigthguess)

Ultimately, with the Bayesian updating method we chose the most probable state from the list of eight states. 